/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author divyanshu
 */
public class controlPanel extends javax.swing.JFrame {

    /**
     * Creates new form controlPanel
     */
    String username;
    int allot;

    public controlPanel() {
        initComponents();
    }
    
    public controlPanel(String s){
        initComponents();
        RoomCB.setEnabled(false);
        this.username = s;
     try{
    Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
      String query = "Select distinct Building_No from Room_Available";
     Statement st = conn.createStatement();
     ResultSet rs = st.executeQuery(query);
     BuildingCB.removeAllItems();
     while(rs.next()){
//         System.out.println(rs.getString("Building_No"));
         
         BuildingCB.addItem(rs.getString("Building_No"));
         
     }
     st.close();
    }catch(Exception e){
    
        System.out.print(e);
   }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RoomCB = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        BuildingCB = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Rooms");

        RoomCB.setEnabled(false);

        jLabel2.setText("Building");

        BuildingCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingCBActionPerformed(evt);
            }
        });

        jButton1.setText("Check Availability");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Fill Application");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(BuildingCB, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(RoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuildingCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(147, 147, 147)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuildingCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingCBActionPerformed
        // TODO add your handling code here:
        
//        RoomCB.setEnabled(true);
        RoomCB.removeAllItems();
try{
        Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
        String build = BuildingCB.getSelectedItem().toString();
        String query = "Select Room_Name from Room_Available where Building_No= '"+build+"'";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(query);
        RoomCB.setEnabled(true);
        while(rs.next())
        {
//            System.out.println();
            RoomCB.addItem(rs.getString("Room_Name"));
        }
        st.close();
}catch(Exception e){
    
}
        
    }//GEN-LAST:event_BuildingCBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
             Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
            String rn = RoomCB.getSelectedItem().toString();
             String query = "Select allotted from Room_Available where Room_Name='"+rn+"'";
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(query);
             rs.next();
             allot = Integer.parseInt(rs.getString("allotted").toString());
             System.out.print(allot);
             if(allot==0){
                 JOptionPane.showMessageDialog(this, "Room Available", "Status of Room", JOptionPane.PLAIN_MESSAGE);
             }
             if(allot==1)
             {
                 JOptionPane.showMessageDialog(this, "Room Not Available", "Status of Room", JOptionPane.ERROR_MESSAGE);
             }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new FIllApplication().setVisible(true);
        String query="";
        try{
        Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
        System.out.print(allot);
        if(allot==0){
            int app_id = generateAPPID();
            query = "insert into Application(Application_ID, Club_ID) values("+app_id+", '"+username+"')";
         Statement st = conn.createStatement();
         st.executeUpdate(query);
         System.out.print(query);
            }
        else{
            JOptionPane.showMessageDialog(this, "Room is already Booked", "Not Available", JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
                    System.out.print("Error in inserting data "+e);
                    
                    
                    }
        
    }//GEN-LAST:event_jButton2ActionPerformed
     public int generateAPPID(){
         try{
         Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
         int a =(int)(Math.floor(Math.random()*1000));
         System.out.print(a);
         String query= "select Application_ID from Application where Application_ID="+a;
         System.out.print(query);
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(query);
//         System.out.print("rs "+rs.getString("Application_ID").toString());
         if(!rs.next())
         {
             return a;
         }
         else
         {
          return generateAPPID();
         }
         }catch(Exception e){
             System.out.print("Error in generating app Id" +e);
         }
         return generateAPPID();
//        System.out.print("Hello");
//        return ;
         }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BuildingCB;
    private javax.swing.JComboBox<String> RoomCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
