/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author divyanshu
 */
public class FIllApplication extends javax.swing.JFrame {

    /**
     * Creates new form FIllApplication
     */
    int allot;
    String username;
    public FIllApplication() {
        initComponents();
        
        
    }
    
       public FIllApplication(String s){
        initComponents();
        RoomCB.setEnabled(true);
       
        this.username = s;
     try{
    Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
      String query = "Select distinct Building_No from Room_Available";
     Statement st = conn.createStatement();
     ResultSet rs = st.executeQuery(query);
      cName.setText(username);
     BuildingCB.removeAllItems();
     while(rs.next()){
//         System.out.println(rs.getString("Building_No"));
         
         BuildingCB.addItem(rs.getString("Building_No"));
         
     }
     st.close();
    }catch(Exception e){
    
        System.out.print(e);
   }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cName = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        eventName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BuildingCB = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        RoomCB = new javax.swing.JComboBox<>();
        date = new datechooser.beans.DateChooserCombo();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Ume P Gothic", 1, 24)); // NOI18N
        jLabel2.setText("Room Booking Application");

        jLabel1.setFont(new java.awt.Font("Ume Gothic C4", 1, 18)); // NOI18N
        jLabel1.setText("Club Name");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Check Availability");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ume P Gothic C4", 1, 18)); // NOI18N
        jLabel3.setText("Event Name");

        jLabel4.setFont(new java.awt.Font("Ume Gothic S4", 1, 18)); // NOI18N
        jLabel4.setText("Date");

        jLabel5.setFont(new java.awt.Font("Ume Gothic S4", 1, 18)); // NOI18N
        jLabel5.setText("Time");

        jLabel6.setFont(new java.awt.Font("Ume P Gothic C4", 1, 18)); // NOI18N
        jLabel6.setText("Building");

        BuildingCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuildingCBActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ume P Gothic C4", 1, 18)); // NOI18N
        jLabel7.setText("Room Number ");

        date.setCalendarPreferredSize(new java.awt.Dimension(500, 500));
        date.setWeekStyle(datechooser.view.WeekDaysStyle.SHORT);

        jLabel8.setText("Enter time in HH:MM:SS  24hrs format");

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(time)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(eventName)
                            .addComponent(cName)
                            .addComponent(BuildingCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RoomCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuildingCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(RoomCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuildingCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuildingCBActionPerformed

        // TODO add your handling code here:
         RoomCB.removeAllItems();
try{
        Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
        String build = BuildingCB.getSelectedItem().toString();
        String query = "Select Room_Name from Room_Available where Building_No= '"+build+"'";
             try (Statement st = conn.createStatement()) {
                 ResultSet rs = st.executeQuery(query);
                 RoomCB.setEnabled(true);
                 while(rs.next())
                 {
//            System.out.println();
                     RoomCB.addItem(rs.getString("Room_Name"));
                 }    }
}catch(Exception e){
    
}   
    }//GEN-LAST:event_BuildingCBActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     try{
        Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
        String RNo = RoomCB.getSelectedItem().toString();
        String BNo = BuildingCB.getSelectedItem().toString();
        String Dt = date.getText();
         String qs = "Select Event_Name from Application where Date=STR_TO_DATE('"+Dt+"','%d/%m/%Y') and Room_Name='"+RNo+"' and Building_No='"+BNo+"'";
//        Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
        System.out.println(qs);
        Statement st2 = conn.createStatement();
        ResultSet rs2 = st2.executeQuery(qs);
//        rs2.next(); 
//        allot = Integer.parseInt(rs.getString("Allotted"));
       
        if(!rs2.next())
        {
            JOptionPane.showMessageDialog(this, "Room Available", "Status of Room", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "Room Not Available", "Status of Room", JOptionPane.ERROR_MESSAGE);
        }
     }
     catch(Exception e)
     {
         
     }
        
              // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
        String CName = cName.getText();
        String EName = eventName.getText();
        String Dt = date.getText();
        String T = time.getText();
        int app_id = generateAPPID();
        
        try{
            Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
            String q = "select datediff(STR_TO_DATE('"+Dt+"','%d/%m/%Y'), curdate()) as days";
        Statement st1 = conn.createStatement();
        ResultSet rs = st1.executeQuery(q);
        rs.next();
        System.out.print(rs.getString("days"));
        if(Integer.parseInt(rs.getString("days"))<0){
         JOptionPane.showMessageDialog(this, "Can't book room before a current date", "Not Available", JOptionPane.ERROR_MESSAGE);   
        }
        else{

        
        
        int hr = Integer.parseInt(T.substring(0,2));
        int min = Integer.parseInt(T.substring(3,5));
        int sec = Integer.parseInt(T.substring(6));
//        System.out.print(hr+":"+min+":"+sec);
        if(hr<24&&hr>17&&min<60&&sec<60){
       
        try{
        String RNo = RoomCB.getSelectedItem().toString();
        String BNo = BuildingCB.getSelectedItem().toString();
        String qs = "Select Event_Name from Application where Date=STR_TO_DATE('"+Dt+"','%d/%m/%Y') and Room_Name='"+RNo+"' and Building_No='"+BNo+"'";
//        Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
        System.out.println(qs);
        Statement st2 = conn.createStatement();
        ResultSet rs2 = st2.executeQuery(qs);
//        rs2.next();
        
        if(!rs2.next()){

//            int app_id = generateAPPID();
            String query = "insert into Application(Application_ID, Club_ID,Event_Name,Date,Time,Room_Name,Building_No) values("+app_id+", '"+CName+"', '"+EName+"', STR_TO_DATE('"+Dt+"','%d/%m/%Y'), '"+T+"', '"+RNo+"','"+BNo+"')";
            Statement st = conn.createStatement();
            System.out.println(query);
            st.executeUpdate(query);
//            System.out.print(query);
            this.dispose();
            new submitapp(app_id, username).setVisible(true);
            }
        else{
            JOptionPane.showMessageDialog(this, "Room is already Booked", "Not Available", JOptionPane.ERROR_MESSAGE);
        }
        }catch(Exception e){
                    System.out.print("Error in inserting data "+e);
                    JOptionPane.showMessageDialog(this, "The time entered is in wrong format", "Wrong Time", JOptionPane.ERROR_MESSAGE);
                    
                    }
        }
                else if(hr>24||min>60||sec>60){
            JOptionPane.showMessageDialog(this, "enter the right date in format HH:MM:SS", "Time Format", JOptionPane.ERROR_MESSAGE);
        }
        else if(hr>21){
            JOptionPane.showMessageDialog(this, "booking is not allowed after 9 p.m.", "Wrong Time", JOptionPane.ERROR_MESSAGE);
        }
        else{
             JOptionPane.showMessageDialog(this, "booking is not allowed before 5 p.m.", "Wrong Time", JOptionPane.ERROR_MESSAGE);
        }
                }
        
            
        }catch(Exception e){
            
        }
//        else if(hr<17){
//            JOptionPane.showMessageDialog(this, "booking is not allowed before 5 p.m.", "Wrong Time", JOptionPane.ERROR_MESSAGE);
//        }

        
    }                                        
     public int generateAPPID(){
         try{
         Connection conn = DriverManager.getConnection(SEProject.myUrl,"root","root");
         int a =(int)(Math.floor(Math.random()*1000));
//         System.out.print(a);
         String query= "select Application_ID from Application where Application_ID="+a;
//         System.out.print(query);
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(query);
//         System.out.print("rs "+rs.getString("Application_ID").toString());
         if(!rs.next())
         {
             return a;
         }
         else
         {
          return generateAPPID();
         }
         }catch(Exception e){
             System.out.print("Error in generating app Id" +e);
         }
         return generateAPPID();
//        System.out.print("Hello");
//        return ;
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new profile(username).setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    
     
    
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIllApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIllApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIllApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIllApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIllApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BuildingCB;
    private javax.swing.JComboBox<String> RoomCB;
    private javax.swing.JTextField cName;
    private datechooser.beans.DateChooserCombo date;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.swing.JTextField eventName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField time;
    // End of variables declaration//GEN-END:variables
}
